### ISSUE TITLE
Convolutional Neural Network Implementation

### ISSUE THREAD

**Issue by k-macmillan** [macattackftw/IntergalacticLifelineI#28]
## Description
Utilize CSV data to implement CNN in order to identify general initial enemy strategy.

## Task Estimate
|| Status | Time | Estimated |
| :-: | :-: | :-: | :-: |
| Research | In progress | ~ | 3:00 |
| Development | Todo | ~ | 12:00 |
| Testing/ Tuning | Todo | ~ | 8:00 | 
|||||
| __Overall__ | In progress | ~ | 23:00 |

**Comment by mwingert96** [comment]
Put in a couple more hours into neural net implementation and theory for ideas, video links for reference:
https://www.youtube.com/watch?v=VrMHA3yX_QI&t=317s
https://www.youtube.com/watch?v=2sevic5Vy4E

**Comment by mwingert96** [comment]
The neural network is written using numpy and the matrix representation of the partial derivatives needed for weight adjustment. It uses matrix multiplication and a sigmoid function for finding the  the likely output, and compares it to a matrix that is evaluated by a score generator using SC2 csv files. it loops through all the files in a directory given and trains on the files then tests the learned info against some hard tests.
    We decided to Use the DTW classify, Since it gives the best answer. The neural network I worked on is having trouble falling into a local min, this means that its giving the answer that all are equally likely since changing any of them slightly causes the error overall to increase. This is likely a result of only having a few layers in the neural net, or the weight modification is adjusting all the values incorrectly.
