### ISSUE TITLE
s2client-api/include/sc2api/config.h doesn't work when building from root directory with cmake

### ISSUE THREAD

**Issue by DGBlueWolf** [macattackftw/IntergalacticLifelineI#36]
## Description
config.h looks for files relative to <project_root>/build when using the current cmake files. 

My fix changed the config file path to "../config.txt" where "config.txt" is in <project_root>.

It would be nice to see the config file implementation more independent of the s2client-api.

Please take a look at it when you get the chance. @mwingert96 

## Task Estimate
| Task | Estimated Time |
| :-:  | :-: |
| Task Name | Time(HH:MM) |
|||

**Comment by k-macmillan** [comment]
Resolved this by changing ../../config.txt to ../../s2client-api/config.txt in config.h
